# Generated by Django 4.2.26 on 2026-07-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_social_protection', '0002_add_malawi_project_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'benefit_plan'), name='uniq_live_project_name_per_plan'),
        ),
    ]
